FROM tensorflow/tensorflow:1.14.0-py3

ENV LANG=C.UTF-8
RUN mkdir /gpt-2
WORKDIR /gpt-2
ADD . /gpt-2
RUN python3 -m pip install --upgrade pip && pip3 install -r requirements.txt
ADD models/ models/
#RUN python3 download_model.py 124M
#RUN python3 download_model.py 355M
#RUN python3 download_model.py 774M
#RUN python3 download_model.py 1558M

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]
